#!/usr/bin/env bash
# Generates AppConfig.swift from the repo's .env.local.
#
# Only the publishable values are read: the Supabase URL and anon key, which
# are designed to ship in clients (RLS is the security boundary, not secrecy).
# SUPABASE_SERVICE_ROLE_KEY and ANTHROPIC_API_KEY are never read here and must
# never reach the app binary.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT/.env.local"
OUT="$ROOT/ios/Astra/Sources/Generated/AppConfig.swift"

[ -f "$ENV_FILE" ] || { echo "error: $ENV_FILE not found" >&2; exit 1; }

read_var() { grep -E "^$1=" "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'" | tr -d '\r'; }

SUPABASE_URL="$(read_var NEXT_PUBLIC_SUPABASE_URL)"
SUPABASE_ANON_KEY="$(read_var NEXT_PUBLIC_SUPABASE_ANON_KEY)"
API_BASE_URL="${ASTRA_API_BASE_URL:-https://astra.shivvyas.com}"

[ -n "$SUPABASE_URL" ] || { echo "error: NEXT_PUBLIC_SUPABASE_URL missing" >&2; exit 1; }
[ -n "$SUPABASE_ANON_KEY" ] || { echo "error: NEXT_PUBLIC_SUPABASE_ANON_KEY missing" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<SWIFT
// Generated by ios/scripts/make-config.sh — do not edit, do not commit.
import Foundation

enum AppConfig {
    static let supabaseURL = URL(string: "$SUPABASE_URL")!
    static let supabaseAnonKey = "$SUPABASE_ANON_KEY"
    static let apiBaseURL = URL(string: "$API_BASE_URL")!
}
SWIFT

echo "wrote $OUT"
