/**
 * TEST-ONLY certificate chains for lib/billing/apple.test.ts, generated with
 * openssl (P-256, valid 2020-01-01 to 2040-01-01). "root" is a self-signed
 * test root, injected into verifyAppleJws through `roots`; production code
 * never sees it and always pins Apple Root CA - G3. The private keys exist
 * only to sign fixtures and protect nothing.
 *
 * - root -> inter (WWDR marker OID) -> leaf (App Store signing marker OID)
 * - plainleaf: issued by inter but without the App Store marker
 * - rogueroot -> rogueinter -> rogueleaf: right OIDs, untrusted root
 */
export const rootPem = `-----BEGIN CERTIFICATE-----
MIIBejCCASCgAwIBAgIUQADDjCSpPNDa2Vr1WqhBTCuOBLwwCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQQXN0cnlhIFRlc3QgUm9vdDAeFw0yMDAxMDEwMDAwMDBaFw00
MDAxMDEwMDAwMDBaMBsxGTAXBgNVBAMMEEFzdHJ5YSBUZXN0IFJvb3QwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAATjxmiZFkQVImZ+kXwHWBioxkOmPn8AZi8U2Kqm
obfJUwhr0+U2Rz92rfERbFtQBy2CF5kmkcgn+F9jokoPU6RVo0IwQDAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUrvkNq9gjSaIVErcT
nIDwYRmgb6wwCgYIKoZIzj0EAwIDSAAwRQIhAJod04pJLU3l4VVvLPHXEk5chC+l
ffGY4/x3kAFEu+4yAiBYWWWIRD2ZNAHWt/ZKyFK+YuuHpvBUGuNinmbY5+em4w==
-----END CERTIFICATE-----`;
export const interPem = `-----BEGIN CERTIFICATE-----
MIIBsDCCAVagAwIBAgIURlTkhh5pV5i4wI8Sz2Th0/j4EzAwCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQQXN0cnlhIFRlc3QgUm9vdDAeFw0yMDAxMDEwMDAwMDBaFw00
MDAxMDEwMDAwMDBaMBsxGTAXBgNVBAMMEEFzdHJ5YSBUZXN0IFdXRFIwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAAQwUWBd1uqyouQ4vekCJupdMCPTjny/SEs2ymhg
qmy0VDYd4jpWFwMyv7szxrowYHBizicSks7T+jVVTcXtLIqZo3gwdjASBgNVHRMB
Af8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAQBgoqhkiG92NkBgIBBAIFADAd
BgNVHQ4EFgQUcFIQbJRbg9pKDfDjYmTaQmGnoGwwHwYDVR0jBBgwFoAUrvkNq9gj
SaIVErcTnIDwYRmgb6wwCgYIKoZIzj0EAwIDSAAwRQIgOjWALs+fdlLDTd1lFHoV
WnvroUrPt+gZ5QDJjSaoGyICIQDZJCLsLPbtQbT1d9wTfH/ipEJ4RPjGkjIStuWm
DNiItg==
-----END CERTIFICATE-----`;
export const leafPem = `-----BEGIN CERTIFICATE-----
MIIBtzCCAV2gAwIBAgIUFjc1FAxSUVC8SY0KQyO4WtlsaMYwCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQQXN0cnlhIFRlc3QgV1dEUjAeFw0yMDAxMDEwMDAwMDBaFw00
MDAxMDEwMDAwMDBaMCgxJjAkBgNVBAMMHUFzdHJ5YSBUZXN0IEFwcCBTdG9yZSBT
aWduaW5nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEToJYnKAupUKKn7hJpXij
saLfkJx/4pnND9IbDnls4+7ppBR2X+mMT7FSWam30/OGWLYVUiYnMT0+HLHOXX2h
nqNyMHAwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwEAYKKoZIhvdjZAYL
AQQCBQAwHQYDVR0OBBYEFBhAu2Nlsb6JlWQDzuinJk4egY4aMB8GA1UdIwQYMBaA
FHBSEGyUW4PaSg3w42Jk2kJhp6BsMAoGCCqGSM49BAMCA0gAMEUCIQDKRpydEA7i
3NWE4jgKeGj6x7IvpEQkYo6x1uZZIpvNOgIgQVlAOvjKC4AtF6+IXT6jq9Cp8o+Z
pmjY5zZclSWQYMY=
-----END CERTIFICATE-----`;
export const plainleafPem = `-----BEGIN CERTIFICATE-----
MIIBojCCAUigAwIBAgIUFjc1FAxSUVC8SY0KQyO4WtlsaMcwCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQQXN0cnlhIFRlc3QgV1dEUjAeFw0yMDAxMDEwMDAwMDBaFw00
MDAxMDEwMDAwMDBaMCUxIzAhBgNVBAMMGkFzdHJ5YSBUZXN0IERldmVsb3BlciBD
ZXJ0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEV9tU9OcQ18UDpHj3FrEKwMfr
lOIkU5XCBL0AV1FPri84mPnwl9b26EUiBJylbcm9HUD87p0BtKXDlJnuvleLNKNg
MF4wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFNQfwLoI
N+jXolL95jgJ9YrpJcIMMB8GA1UdIwQYMBaAFHBSEGyUW4PaSg3w42Jk2kJhp6Bs
MAoGCCqGSM49BAMCA0gAMEUCID+dw+8BcOCVcl43jBlwuwNL6NwBkQAkhvcIMmng
1NCwAiEA/M18x9cieqC9o6pat9WEhX65rLAh0uUSelU5lBKYV/M=
-----END CERTIFICATE-----`;
export const roguerootPem = `-----BEGIN CERTIFICATE-----
MIIBbzCCARSgAwIBAgIUAJRqvnD95XucDaRj34ykTS+ALBcwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKUm9ndWUgUm9vdDAeFw0yMDAxMDEwMDAwMDBaFw00MDAxMDEw
MDAwMDBaMBUxEzARBgNVBAMMClJvZ3VlIFJvb3QwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAARWHHho+CKY7WWUFW6iK7EbpqHWWZFCDbpDf7ljdRpW0R/9PUR2s9Zh
ix4BEosPbYVupSsMMJKsNP3513EMR3Lto0IwQDAPBgNVHRMBAf8EBTADAQH/MA4G
A1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUAZqkakzIJC+TF9PQ/ezrdi9CDPswCgYI
KoZIzj0EAwIDSQAwRgIhAPJFGSNs3vZ6lINDWZ1D1vPycRzQM2oKYjr7E70aXqNc
AiEAvBBNB1UxcmmHBR+c2x2DVw4OOtGqIXWp5a03eXnTzT4=
-----END CERTIFICATE-----`;
export const rogueinterPem = `-----BEGIN CERTIFICATE-----
MIIBozCCAUqgAwIBAgIUENK3UKiirjaGFvU1S6EtmaX9THIwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKUm9ndWUgUm9vdDAeFw0yMDAxMDEwMDAwMDBaFw00MDAxMDEw
MDAwMDBaMBUxEzARBgNVBAMMClJvZ3VlIFdXRFIwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAARbwYoZGM1OGDT6kRHxDNCDJOV1qIxu+LxMThnIhaFItTu5ai9xXN3O
e/3+xdyxo6+m7F2ZgFNSD4oEh+nkYbwlo3gwdjASBgNVHRMBAf8ECDAGAQH/AgEA
MA4GA1UdDwEB/wQEAwIBBjAQBgoqhkiG92NkBgIBBAIFADAdBgNVHQ4EFgQUQ4JQ
HzQfIshV+YQIsgCrysIUnOYwHwYDVR0jBBgwFoAUAZqkakzIJC+TF9PQ/ezrdi9C
DPswCgYIKoZIzj0EAwIDRwAwRAIgSf1EbNqzONIqeJN2hgQxuyOU3dcS6vjcb+Qa
rI7nwvUCIACYKusDtprbNKbkic99LjWNDuIcRl6hfGfWto3PluRG
-----END CERTIFICATE-----`;
export const rogueleafPem = `-----BEGIN CERTIFICATE-----
MIIBojCCAUegAwIBAgIUMbBG/0jWlJu4c2O7Rh6s3tWyCrkwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKUm9ndWUgV1dEUjAeFw0yMDAxMDEwMDAwMDBaFw00MDAxMDEw
MDAwMDBaMBgxFjAUBgNVBAMMDVJvZ3VlIFNpZ25pbmcwWTATBgcqhkjOPQIBBggq
hkjOPQMBBwNCAAQpmZoZN6HYIc8vPuXPoZEJ9h6VmeTB6IfA+8nMUhWznb/nDOPY
/H4ehdB7KgYBp/7T/BDkxeRwrBcmchii9pnuo3IwcDAMBgNVHRMBAf8EAjAAMA4G
A1UdDwEB/wQEAwIHgDAQBgoqhkiG92NkBgsBBAIFADAdBgNVHQ4EFgQUzYih4g8A
KSJc844+t7M/QaG1p5YwHwYDVR0jBBgwFoAUQ4JQHzQfIshV+YQIsgCrysIUnOYw
CgYIKoZIzj0EAwIDSQAwRgIhAK47uzQ4e0b84wjTAwZvcbAC3pbd+83JyyeA9t2l
YnhIAiEA6gzcrpkEy74tMh6oSipp9RZe4BBBXT6hiG7xh9/Jh08=
-----END CERTIFICATE-----`;
export const leafKey = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg1sAz4m4YHzvl10SO
g2mmw6ExNGs4lM0R4gIOkBZWIJehRANCAAROglicoC6lQoqfuEmleKOxot+QnH/i
mc0P0hsOeWzj7umkFHZf6YxPsVJZqbfT84ZYthVSJicxPT4csc5dfaGe
-----END PRIVATE KEY-----`;
export const plainleafKey = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgSE8V0wT3GKo3Bknx
KCU0ylWlaLlpEiy6s3qyc5RZPHOhRANCAARX21T05xDXxQOkePcWsQrAx+uU4iRT
lcIEvQBXUU+uLziY+fCX1vboRSIEnKVtyb0dQPzunQG0pcOUme6+V4s0
-----END PRIVATE KEY-----`;
export const rogueleafKey = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg26cctDyinJB6iXK9
YAJNE8OcrNjcoYcF4RjO1Of9aDahRANCAAQpmZoZN6HYIc8vPuXPoZEJ9h6VmeTB
6IfA+8nMUhWznb/nDOPY/H4ehdB7KgYBp/7T/BDkxeRwrBcmchii9pnu
-----END PRIVATE KEY-----`;
